### ISSUE TITLE
Panel with 0 children brings fps to 5

### ISSUE THREAD

**Issue by teotigraphix** [BowlerHatLLC/feathers#1358] opened 2016-04-27 20:16 UTC
I haven't debugged it to the point to see what is recursing or constantly firing but it might have to do with those min sizes you did.

I just wanted to see if you can verify this or is it something I am doing.

**Comment by joshtynjala** [comment] 2016-04-27 20:22
Yeah, it's probably the minimum sizing calculating something wrong, and invalidating every frame. I'll take a look.

**Comment by teotigraphix** [comment] 2016-04-27 21:01
Hey,

Just to recreate what I have, it's actually a Panel holding Panel children inside a left drawer. The Panel in the drawer content has a VerticalLayout. The child Panels have no layout data either, the main Panel has minWidth set to 300.

So its;

LeftDrawer content
- Panel
  - Panel
  - Panel
  - Panel

If the child Panel has 0 children it happens, I haven't tested any other scenario right now.

**Comment by joshtynjala** [comment] 2016-04-27 21:28
I tried with the following code, but I couldn't reproduce. The issue may have been fixed in my latest code, though. Is there any chance that you're using distributeHeights on the VerticalLayout?

	new MetalWorksMobileTheme();

	var drawers:Drawers = new Drawers();
	drawers.content = new LayoutGroup();
	this.addChild(drawers);
	
	var outerLayout:VerticalLayout = new VerticalLayout();
	outerLayout.horizontalAlign = HorizontalAlign.JUSTIFY;

	var outerPanel:Panel = new Panel();
	outerPanel.title = "Panels";
	outerPanel.layout = outerLayout;
	outerPanel.minWidth = 300;
	var panel1:Panel = new Panel();
	panel1.title = "One";
	outerPanel.addChild(panel1);
	var panel2:Panel = new Panel();
	panel2.title = "Two";
	outerPanel.addChild(panel2);
	var panel3:Panel = new Panel();
	panel3.title = "Three";
	outerPanel.addChild(panel3);
	drawers.leftDrawer = outerPanel;

Also, I assume you're on 3.0.0-beta rather than the older 3.0.0-alpha?

**Comment by teotigraphix** [comment] 2016-04-27 21:39
I am using sdk beta. I am not using any distribute heights.

I will try tomorrow to see if I can get something vanilla to reproduce it. It's just buried in my code so maybe it's something I am doing with the custom component.

**Comment by teotigraphix** [comment] 2016-04-27 21:42
This is what I am using, they are collapsible panes. If I take something 1 & 2 out of that panel it dies.

https://snag.gy/YVucg1.jpg

**Comment by teotigraphix** [comment] 2016-04-27 21:47
Hmm, I have to get better about explaining what I am doing. I actually had to hack something because the real problem was inlcudeInLayout.

I am just looking at my code again.

There is a List in the child Panels, which when I first wrote the components, I had isOpen and when it was false, I was trying to set visible and includeInLayout to false on the child List.

This is where I was initially having the problem. I need to investigate more I guess.

**Comment by joshtynjala** [comment] 2016-04-27 21:51
If they're a subclass of panel, and you've overridden anything related to how it measures itself (or sets the dimensions on the header), you may need to update that code to match the changes in Panel/Scroller.

**Comment by teotigraphix** [comment] 2016-04-27 21:51
Try adding a List to a child and set the visible and includeInLayout to false.

**Comment by teotigraphix** [comment] 2016-04-27 21:52
No I didn't override any measurements or layout code. Let me rewrite to component tommarrow and I will see what happens.

**Comment by joshtynjala** [comment] 2016-04-27 22:10
> Try adding a List to a child and set the visible and includeInLayout to false.

Oops! I forgot to check for includeInLayout in an overridden method. Fixed!

**Comment by teotigraphix** [comment] 2016-04-27 22:14
Ha, so I wasn't crazy, sorry about the nosie at the start of the issue. :)

**Comment by joshtynjala** [comment] 2016-04-27 22:18
I never could reproduce the FPS drop, though, so if you can figure out if that's a Feathers issue, let me know. I'm going to close this for now, but you can reopen it, if needed.

**Closed by joshtynjala** 2016-04-27 22:18 UTC
Labels: bug

**Comment by teotigraphix** [comment] 2016-04-27 22:20
Yeah the component was a first iteration, you know how that is. :) But the includeInLayout was weird.

If it comes up again, I will make sure to have a repro case.
