### ISSUE TITLE
Scroller: How to deal with the scrolling of dynamic lists

### ISSUE THREAD

**Issue by GV3** [BowlerHatLLC/feathers#1468] opened 2016-09-28 01:30 UTC
I'm having the following issue today and decided to drop a line just to confirm if this is the expected behavior or if I'm missing something.

I have a vertical List which initially has 30 items although it displays 10. This list is receiving items from the server dynamically to both ends. 

When the items are pushed at the bottom of the list the list behaves perfectly, nothing moves and the items are correctly placed waiting for the user to scroll.

On the other hand, when the items are added at the beginning of the list the List jumps visually, in what I suppose that an attempt to keep the same vertical scroll position.

Is this the expected behavior? 

if yes, Can it be contra rested? Is there a defacto way the community uses to avoid this jump when adding items at the beginning of the collection?

Should I just try to scroll the list to the previous position after the items were added?

These new items should be added anytime, even if the user is manually scrolling, and it would be great if adding at the first positions would be as unnoticeable as at the end.

Thanks in advance for any thoughts!

**Comment by joshtynjala** [comment] 2016-09-28 15:51
> On the other hand, when the items are added at the beginning of the list the List jumps visually, in what I suppose that an attempt to keep the same vertical scroll position.

Can you clarify? Does the verticalScrollPosition stay the same, and the items in view change? Or is it that the verticalScrollPosition changes, and the items in view remain the same?

**Comment by joshtynjala** [comment] 2016-09-28 15:57
Also, I think [the forums](http://forum.starling-framework.org/) is a better place for discussion. We can certainly open an issue once we've figured out the details of anything that should change in Feathers, but I try to keep Github focused on specific, non-ambiguous bug reports and feature requests. If an issue is a discussion/conversation, it's never clear when it's "done" and when the not-exactly-an-issue should be closed. I don't like things floating around in my issue tracker like that. I'm going to close this now, but since we've already started chatting here, you can continue to comment.

**Closed by joshtynjala** 2016-09-28 15:57 UTC

**Comment by GV3** [comment] 2016-09-28 20:28
Hi, Josh

> Can you clarify? Does the verticalScrollPosition stay the same, and the items in view change? Or is it that the verticalScrollPosition changes, and the items in view remain the same?

I can confirm now that when new items are added at the beginning of the array the verticalScrollPosition remains the same while the maxVerticalScrollPosition increases, because of this the items displayed on the screen are immediately displayed X amount of pixels lower on the list ( X being the new amount added to the maxVerticalScrollPosition).

For me, this as a bug and this is why I post it here. I still prefered to ask if this is the expected behavior, by design, instead of  jumping to call it a bug.

I completely understand your request and will in the future be more careful about posting here more nonambiguous reports and use the Forums discussion or conversation.

**Comment by joshtynjala** [comment] 2016-09-28 21:00
This is indeed the expected behavior. I just checked, and Flex does not adjust the scroll position when adding new items to the beginning of the data provider either. To be honest, I would be surprised if any UI framework did that.

So, to answer this question from your original post:

> Should I just try to scroll the list to the previous position after the items were added?

Yes. Since you know it's a VerticalLayout, you can probably simply use the value of the old maxVerticalScrollPosition and the new one to figure out how far to move.

You may run into issues trying to change verticalScrollPosition programatically when the user is dragging the list to scroll at the same time, though. If you find that this is true, I may be able to make some changes to Scroller to account for that. Let me know what you find!
