### ISSUE TITLE
backgroundSkin bug after updating to Feathers 3.0 (commit: ee0020d) with Starling 2.0

### ISSUE THREAD

**Issue by GV3** [BowlerHatLLC/feathers#1266] opened 2015-12-21 12:36 UTC
The update worked perfectly, and many of the improvements are obvious. Specially on the text renderer.

The bug though is ocurring when skinning the background of some components, as a "LayoutGroupListItemRenderer" and a "LayoutGroup" Where the Background is not displaying as it should. It looks as if it would be using some kind of blend mode and with 0.1 alpha.

I had to manually add the same Scale9Image as a Background and resize it via draw().

The rest of the components seem to be drawing and displaying the backgrounds as they should.

**Comment by joshtynjala** [comment] 2015-12-21 18:52
Thank you. I didn't have much time to dig into the new rendering architecture to figure out how to render the background while not exposing it as a child with functions like getChildAt(). I'll get it fixed once get more familiar with Starling 2.0's changes.

**Comment by GV3** [comment] 2015-12-27 15:54
I can still reproduce the error.

Also, I don't know if it's related... But I have, since I use Feathers 3.0 with Starling 2.0 the Lists displaying the content out of the specified inbound. (See image)

<img width="307" alt="screen shot 2015-12-27 at 4 47 23 pm" src="https://cloud.githubusercontent.com/assets/1840077/12010910/601a7ae4-acba-11e5-8b00-560c145f06fc.png">

**Comment by joshtynjala** [comment] 2015-12-27 16:49
You need to enable depth and stencil in your application descriptor. It is required for masks. After Daniel starts supporting clip rects internally for rectangular masks, you'll be able to disable it.

**Comment by GV3** [comment] 2015-12-27 18:28
Done, enabling the depth and stencil fixed the problem on the image. 

I still have the background BUG described above though...

"
The bug though is ocurring when skinning the background of some components, as a "LayoutGroupListItemRenderer" and a "LayoutGroup" Where the Background is not displaying as it should. It looks as if it would be using some kind of blend mode and with 0.1 alpha.

I had to manually add the same Scale9Image as a Background and resize it via draw().

The rest of the components seem to be drawing and displaying the backgrounds as they should.
"

**Comment by joshtynjala** [comment] 2015-12-27 19:23
You still can't see the background at all?

**Comment by GV3** [comment] 2015-12-27 19:57
That is correct

**Comment by joshtynjala** [comment] 2015-12-27 21:49
Okay, I'll look again. Maybe my code didn't account for Starling's new automatic caching system properly.

By the way, the discoloration that you see, where it looks like there's something with alpha 0.1 or a blend mode is unrelated to the LayoutGroup background. It seems to be related to masking. I dint yet know if it's a Starling bug or a Feathers bug.

**Comment by joshtynjala** [comment] 2016-01-23 00:46
The following code can reproduce this issue. When the delayed call attempts to change the background of the second LayoutGroup, it doesn't work, and the original background is still visible.

	var group:LayoutGroup = new LayoutGroup();
	group.backgroundSkin = new Quad(100, 100, 0x00ff00);
	group.move(10, 10);
	this.addChild(group);

	var group2:LayoutGroup = new LayoutGroup();
	group2.move(10, 120);
	group2.backgroundSkin = new Quad(100, 100, 0xff0000);
	this.addChild(group2);
	Starling.juggler.delayCall(function():void
	{
		trace("change background!");
		group2.backgroundSkin = new Quad(100, 100, 0x00ff00);
	}, 0.5);

**Closed** 2016-02-04 21:53 UTC
Labels: bug
