### ISSUE TITLE
SpinnerList not selecting last item

### ISSUE THREAD

**Issue by dannycortesv** [BowlerHatLLC/feathers#1532] opened 2017-02-02 13:48 UTC
I'm having issues on iOS and Android, seems that in some cases when we have few items, the last one is not been able to select, look at the video: https://www.screencast.com/t/OuBiLCqYnQD

**Comment by dannycortesv** [comment] 2017-02-02 14:06
I think this is happening due that _verticalPageIndex is equal to itemCount, so the pageIndex turns 0, but not itemCount-1, this happen when the list data is not enough to make the component a loop.

**Comment by dannycortesv** [comment] 2017-02-02 14:35
I solved using this on the spinnerList_scrollCompleteHandler:


if(this._maxVerticalPageIndex != this._minVerticalPageIndex)
			{
				var pageIndex:int;
				
				if(itemCount>3){
					pageIndex = this._verticalPageIndex % itemCount;
				}else{
					if(this._verticalPageIndex == itemCount){
						pageIndex=itemCount-1;
					}else{
						pageIndex = this._verticalPageIndex % itemCount;
					}
				}
			}

**Comment by joshtynjala** [comment] 2017-02-03 17:21
@dannycortesv I was not able to reproduce with the code that you posted in #1493. Here's a simplified version that I created that doesn't have any external dependencies and doesn't need a theme:

	var spinner:SpinnerList = new SpinnerList();
	spinner.x = 20;
	spinner.y = 20;
	spinner.dataProvider = new ListCollection(
	[
		{ label: "One"},
		{ label: "Two"},
		{ label: "Three"},
	]);
	spinner.backgroundSkin = new Quad(1, 1, 0xffffff);
	spinner.width = 200;
	spinner.height = 150;
	spinner.itemRendererFactory = function():DefaultListItemRenderer
	{
		var renderer:DefaultListItemRenderer = new DefaultListItemRenderer();
		renderer.defaultSkin = new Quad(1, 1, 0xcccccc);
		renderer.defaultSelectedSkin = new Quad(1, 1, 0xff00ff);
		return renderer;
	}
	this.addChild(spinner);

Can you modify this code to make it reproduce the issue? I suspect that it will have something to do with the height of the SpinnerList and the height of the item renderers.

**Comment by joshtynjala** [comment] 2017-03-22 16:30
Closing. Please feel free to reopen if you can provide more information.

**Closed by joshtynjala** 2017-03-22 16:30 UTC
Labels: waiting-for-response
