### ISSUE TITLE
TextInput Select text indication get stuck in ipad 4 with ios 9

### ISSUE THREAD

**Issue by rlowczy** [BowlerHatLLC/feathers#1396] opened 2016-06-06 08:04 UTC
Hey there.
I am frontend as3/flex developer from company called YDP (Young Digital Planet).

Im working right now on text selection issue .
The bug is showed properly on attached video file. Please see it.

As you can see (i hope) when you open component that contains Feather's TextInput. It behave strangely by selecting itself few times.

Currently we are using feathers 1.3.0 and it would be really complicated to upgrade it to higher version.
Im not telling its impossible but it would probably burn a lot (i mean really a lot) of hours.

```
private function textInputInitializer(textInput:TextInput):void
{
textInput.textEditorFactory = function():StageTextTextEditor{return new StageTextTextEditor()};
   textInput.textEditorProperties.color = styles.note.noteTextFontColor;
   textInput.textEditorProperties.fontFamily = FontsHolder.REGULAR_FONT;
   textInput.textEditorProperties.fontSize = TEXT_INPUT_FONT_SIZE * ThemeBase.DPI_SCALE;
   textInput.textEditorProperties.textAlign = TextAlign.LEFT;
   textInput.textEditorProperties.multiline = true;
   textInput.textEditorProperties.wordWrap = true;
   textInput.promptProperties.textFormat = new TextFormat(FontsHolder.REGULAR_FONT, TEXT_INPUT_FONT_SIZE * ThemeBase.DPI_SCALE, styles.note.noteTextFontColor, null, null, null, null, null, TextAlign.LEFT);
   textInput.promptProperties.embedFonts = true;
}
````

This is the initializer for this specific TextInput.
From what i see. It happend when multiline is true.

Cheers!

[annotation_bug3.zip](https://github.com/BowlerHatLLC/feathers/files/299926/annotation_bug3.zip)

**Comment by joshtynjala** [comment] 2016-06-06 17:28
With StageTextTextEditor, text selection behavior is completely controlled by flash.text.StageText. It looks like a bug in AIR, but I guess I can imagine ways that StageTextTextEditor might be showing its texture snapshot incorrectly or somehow creating multiple StageText instances.

Have you tried connecting your app to the debugger while it's running on the device to see if there are any runtime errors being thrown? The app will keep running after a runtime error, but the current call stack is aborted, so that can often cause strange behaviors like what we see here.

You could try using TextFieldTextEditor instead. It works on mobile, but you may lose certain features (which may or may not be necessary).

If you decide to try upgrading Feathers, versions 2.0 - 2.2 will probably be the easiest. Some things are deprecated, but you won't be forced to make certain changes until 2.3. It's also worth noting that you don't need to upgrade your theme away from the DisplayListWatcher class in Feathers 2.x. It's encouraged, but not necessary. Of course, if this is an AIR bug, upgrading Feathers won't help.

**Comment by rlowczy** [comment] 2016-06-08 09:52
Thanks for quick response!
We will take a look at this issue and try few ways to fix it!

Thanks and cheers!

**Comment by joshtynjala** [comment] 2016-06-08 14:17
I'm going to close this issue, since Feathers 1.3.0 is no longer maintained. However, if you have further questions, you may post them here even after it is closed, or you can visit the [forum](http://forum.starling-framework.org/forum/feathers).

**Closed by joshtynjala** 2016-06-08 14:17 UTC

**Comment by 5minutes2start** [comment] 2016-07-04 06:05
Hi Josh,

It seems that this problem is related to StageTextTextEditor and it can be reproduced in the newest Feathers.
This problem do not happen if to use StageText directly.

thanks,

**Comment by joshtynjala** [comment] 2016-07-04 16:14
Can you put together some simple code that will consistently reproduce the issue in Feathers 3? I'll be happy to take a look.

**Comment by 5minutes2start** [comment] 2016-07-06 11:46
Hi Josh, thanks for quick answer.
To make it clear - by "bug" I mean text selection flickering.

When you use plain StageText and give it focus - it will just place text caret on position where you touched it.

When you use feathers TextInput with StageTextTextEditor, it will cause additional text selection flickering.

I believe code below is enough:

```
private function createText():void
		{
			textInput.textEditorFactory = function ():StageTextTextEditor
			{
				return new StageTextTextEditor()
			};
			textInput.textEditorProperties.fontSize = 40;
			textInput.textEditorProperties.color = 0x000000;
			textInput.textEditorProperties.multiline = true;
			textInput.textEditorProperties.fontFamily = "Arial";
			textInput.promptProperties.embedFonts = true;
			textInput.promptProperties.multiline = true;
			textInput.promptProperties.wordWrap = true;
			textInput.width = 200;
			textInput.height = 500;
			textInput.x = 40;
			textInput.y = 100;
			textInput.text = 'first\nsecond\nthird\nfourth';
			addChild(textInput);
		}
```

**Comment by joshtynjala** [comment] 2016-07-18 16:52
@5minutes2start I'm afraid that I'm not seeing any flickering issues with the code that you provided.
