### ISSUE TITLE
Error on latest version and on the beta version (null reference)

### ISSUE THREAD

**Issue by bilicio** [BowlerHatLLC/feathers#1537] opened 2017-02-23 21:32 UTC
TypeError: Error #1009: Cannot access a property or method of a null object reference.
	at feathers.controls.renderers::BaseDefaultItemRenderer/refreshSelectionEvents()[C:\Projetos\Rally\Projeto Rally\src\feathers\controls\renderers\BaseDefaultItemRenderer.as:5807]
	at feathers.controls::ToggleButton/draw()[C:\Projetos\Rally\Projeto Rally\src\feathers\controls\ToggleButton.as:1327]
	at feathers.controls.renderers::BaseDefaultItemRenderer/draw()[C:\Projetos\Rally\Projeto Rally\src\feathers\controls\renderers\BaseDefaultItemRenderer.as:4451]

Error on this three:

this.tapToSelect.isEnabled = selectionEnabled;
this.tapToSelect.tapToDeselect = this._isToggle;
this.keyToSelect.isEnabled = false;

thank you josh!

**Comment by joshtynjala** [comment] 2017-02-23 22:13
Can you provide some code that will reproduce the issue? I'm not seeing this error when I create a List.

**Comment by bilicio** [comment] 2017-02-24 13:39
this app was built with the last version of feathers, starling and AIR. Im updating the app to release new features, so i dont know where this error came from because is in the list phase. I will make some breakpoints along the way to find the specific error point.

thank you!

**Comment by bilicio** [comment] 2017-02-24 13:51
The problem is associated to the GroupedList.

**Comment by joshtynjala** [comment] 2017-02-24 15:58
It appears that your itemRendererFactory doesn't return anything. It should always return a new item renderer. Or did you simply remove the code in the body of the function?

There's not much I can do without more information, so sharing some real code will help. Otherwise, I'll just need to close this issue because I cannot reproduce.

**Comment by bilicio** [comment] 2017-02-24 17:32
Alright sorry for that.. i saw that this override function doesnt exist anymore:
override protected function itemRenderer_triggeredHandler

im using it and i comment to execute the app to get rid of the error. i will compare the DefaultGroupedListItemRendered New to my old Item Rendered.

**Comment by bilicio** [comment] 2017-02-24 17:40
This is my complete item render.. maybe now i need to override another function to work?

`package com.renderers
{
	import com.antidoto.loadImage;
	
	import feathers.controls.Button;
	import feathers.controls.Label;
	import feathers.controls.renderers.DefaultGroupedListItemRenderer;
	
	import starling.display.DisplayObject;
	import starling.display.Sprite;
	import starling.events.TouchEvent;
	import starling.events.TouchPhase;
		
	public class ListaContatosItemRenderer extends DefaultGroupedListItemRenderer
	{
		private var editButton:Button;
		private var convidadoImage:Sprite;
				
		private var _oText:String;
		private var label:Label;
		
		private static const CHAR_LIMIT:int = 30;
		
		private var dispachar:Boolean = true;
		
		public var editarContatoHandler:Function;
								
		public function ListaContatosItemRenderer(editHandler:Function)
		{
			editarContatoHandler = editHandler;
			
		}
						
		override protected function initialize():void
		{					
			editButton = new Button();
			editButton.label = "EDITAR";
			editButton.x = 300;
			editButton.y = 5;
			setChildIndex(editButton, numChildren-1);
			editButton.addEventListener(TouchEvent.TOUCH, editarClick);
			addChild(editButton);
			//REAJUSTED
			//editButton.flatten();
			
		}						
		
		
		
		override protected function commitData():void
		{			
			
			if(this._data !== null && this._owner)
			{
				if(this._itemHasLabel)
				{
					if (this.itemToLabel(this._data).length > CHAR_LIMIT)
						this._label = this.itemToLabel(this._data).slice(0, CHAR_LIMIT) + "...";
					else
						this._label = this.itemToLabel(this._data);										
					
					if (this._data.convidado){
						convidadoImage = new loadImage("conv_selected", true);
						convidadoImage.x = 255;
						convidadoImage.y = 12;
						addChild(convidadoImage);
					}else{
						convidadoImage = new loadImage("conv_unselected", true);
						convidadoImage.x = 255;
						convidadoImage.y = 12;
						addChild(convidadoImage);
					}
					
					//this.flatten();		//testar performance			
				}
				if(this._itemHasSkin)
				{
					var newSkin:DisplayObject = this.itemToSkin(this._data);
					this._skinIsFromItem = newSkin != null;
					this.replaceSkin(newSkin);
				}
				else if(this._skinIsFromItem)
				{
					this._skinIsFromItem = false;
					this.replaceSkin(null);
				}
				if(this._itemHasIcon)
				{
					var newIcon:DisplayObject = this.itemToIcon(this._data);
					this._iconIsFromItem = newIcon != null;
					this.replaceIcon(newIcon);
				}
				else if(this._iconIsFromItem)
				{
					this._iconIsFromItem = false;
					this.replaceIcon(null);
				}
				if(this._itemHasAccessory)
				{
					var newAccessory:DisplayObject = this.itemToAccessory(this._data);
					this._accessoryIsFromItem = newAccessory != null;
					this.replaceAccessory(newAccessory);
				}
				else if(this._accessoryIsFromItem)
				{
					this._accessoryIsFromItem = false;
					this.replaceAccessory(null);
				}
				if(this._itemHasSelectable)
				{
					this._isToggle = this._explicitIsToggle && this.itemToSelectable(this._data);
				}
				else
				{
					this._isToggle = this._explicitIsToggle;
				}
				if(this._itemHasEnabled)
				{
					this.refreshIsEnabled(this._explicitIsEnabled && this.itemToEnabled(this._data));
				}
				else
				{
					this.refreshIsEnabled(this._explicitIsEnabled);
				}
			}
			else
			{
				if(this._itemHasLabel)
				{
					this._label = "";
				}
				if(this._itemHasIcon || this._iconIsFromItem)
				{
					this._iconIsFromItem = false;
					this.replaceIcon(null);
				}
				if(this._itemHasSkin || this._skinIsFromItem)
				{
					this._skinIsFromItem = false;
					this.replaceSkin(null);
				}
				if(this._itemHasAccessory || this._accessoryIsFromItem)
				{
					this._accessoryIsFromItem = false;
					this.replaceAccessory(null);
				}
				if(this._itemHasSelectable)
				{
					this._isToggle = this._explicitIsToggle;
				}
				if(this._itemHasEnabled)
				{
					this.refreshIsEnabled(this._explicitIsEnabled);
				}
			}
			
		}				
		
		// REAJUSTED
		/*override protected function itemRenderer_triggeredHandler(event:Event):void{
			if (dispachar){				
				//removeChild(convidadoImage);
				//convidadoImage = new loadImage("convSelected", true);
				//convidadoImage.x = 255;
				//convidadoImage.y = 12;
				//addChild(convidadoImage);		
				super.itemRenderer_triggeredHandler(event);				
			}else{
				dispachar = true;
			}
		}*/
		
		private function editarClick(evt:TouchEvent):void
		{
			if(!evt.getTouch(evt.currentTarget as Button, TouchPhase.ENDED))
				return;
			
			editarContatoHandler(this._data);
			dispachar = false;	
		}
								
						
	}
}`

**Comment by joshtynjala** [comment] 2017-02-24 17:46
The TapToTrigger utility now handles dispatching Event.TRIGGERED. You may be able to temporarily disable it to achieve the same behavior.

**Comment by bilicio** [comment] 2017-02-24 18:10
Besides the initialize and commitdata functions is there any function i need to override preferably to my ItemRenderer work?

**Comment by joshtynjala** [comment] 2017-02-24 18:16
Can you be more specific? What's not working?

**Comment by bilicio** [comment] 2017-02-24 18:23
This itemrender there i create gives me that error i post since feathers 3.0 . i think i need to override a new function to work.  the commented Triggered gives me another error. so forget about the triggered event. i dont know why this itemrender wont work anymore.

Im sorry to keep you busy looking for errors. Its better i take a look on the changes since feathers 2.0 to realize what im missing or its wrong with the code.

**Comment by joshtynjala** [comment] 2017-02-24 18:33
It looks like you forgot to call super.initialize() in your override of initialize().

**Comment by bilicio** [comment] 2017-02-24 18:39
Thats it Josh!!! so simple! i dont know why this works in 2.0 without it! thank you so much! and sorry about it!

**Comment by joshtynjala** [comment] 2017-02-24 18:44
It's likely that initialize() was empty in 2.0. However,

**Closed by joshtynjala** 2017-02-24 18:44 UTC
Labels: waiting-for-response
