### ISSUE TITLE
DefaultFocusManager.set focus() exception

### ISSUE THREAD

**Issue by tconkling** [BowlerHatLLC/feathers#1374] opened 2016-05-15 19:33 UTC
I'm updating to Starling 2.0 and Feathers 3.0.0b (using the latest version, adf3a1b), and I'm having an issue in `DefaultFocusManager`.

On line 231, `this._focus` can be null, causing a NullPointerException:
```actionscript
if(this._isEnabled)
{
    if(this._focus)
    {
        if(this._focus is INativeFocusOwner)
        {
            nativeStage.focus = INativeFocusOwner(this._focus).nativeFocus; // <-- set focus() can be called recursively here, causing this._focus to be null, below
        }
        //an INativeFocusOwner may return null for its
        //nativeFocus property, so we still need to double-check
        //that the native stage has something in focus. that's
        //why there isn't an else here
        if(!nativeStage.focus)
        {
            nativeStage.focus = this._nativeFocusTarget;
        }
        nativeStage.focus.addEventListener(FocusEvent.FOCUS_OUT, nativeFocus_focusOutHandler, false, 0, true);
        this._focus.dispatchEventWith(FeathersEventType.FOCUS_IN); // <-- line 231, this._focus NullPointerException
    }
    else
    {
        nativeStage.focus = null;
    }
}
```

This happens when `DefaultFocusManager.set focus()` is called recursively; in my case, when the call to `nativeStage.focus = INativeFocusOwner(this._focus).nativeFocus;` on line 220 is executed, and causes a `TextInput`'s `textEditor_focusOutHandler()` method to be called, which sets `this._focusManager.focus = null`, which means that the `DefaultFocusManager`'s _focus member is null when the original call to `set focus()` continues.

I haven't really dived into the code other than to see what was causing my exception, but it seems like it makes sense to guard against recursive `set focus()` calls in DefaultFocusManager. I'm happy to make a pull request for this - please let me know!

Thanks!

**Comment by joshtynjala** [comment] 2016-05-17 21:28
I'm not able to reproduce with a project that has multiple TextInputs on screen. Can you try to put together some simple code that reproduces the issue?

I could guard against recursive set focus calls, but that would likely result in new issues elsewhere. I'd rather track down the real source of the bug.

**Comment by tconkling** [comment] 2016-05-18 00:13
[FeathersTest.zip](https://github.com/BowlerHatLLC/feathers/files/269406/FeathersTest.zip)

I've attached a sample app. The main class file is at `ftest.FeathersTestApp.as`. (There's also an IntelliJ project in there, if that makes things more convenient.)

`test.FeathersTestApp.as`, line 24, exhibits the bug I reported.

**Comment by joshtynjala** [comment] 2016-05-18 15:58
Oh, I have an idea what's going on. StageTextTextEditor has a null nativeFocus property because StageText isn't an InteractiveObject. The DefaultFocusManager is pulling focus away from the StageText, and that's resulting in the _focus variable being set to null.

Strangely, using Keyboard.TAB still works to change focus with StageTextTextEditor, so I'm not sure why that's not triggering the same behavior. I'll investigate.

As a workaround for now, I recommend using a different ITextEditor. Other text editors are better for desktop apps anyway.

**Comment by tconkling** [comment] 2016-05-18 17:19
Thanks for looking into this, Josh.

My game is on mobile as well as desktop, which is why I went with a StageTextTextEditor - I need the soft keyboard on iPhones and Androids. (I can certainly a different ITextEditor for desktop builds, of course.)

**Comment by joshtynjala** [comment] 2016-05-19 16:24
This should be fixed in the latest commits.

**Closed by joshtynjala** 2016-05-19 16:24 UTC
Labels: bug
