### ISSUE TITLE
PopUpManager.popups

### ISSUE THREAD

**Issue by manofspirit** [BowlerHatLLC/feathers#1211] opened 2015-09-26 10:38 UTC
should return all the opened popups so we can do tasks such as
- close all the popups
- etc

**Comment by joshtynjala** [comment] 2015-09-28 16:09
PopUpManager.root may be useful here. If you pass your own Sprite to PopUpManager.root, you may be able to simply call PopUpManager.root.removeChildren() to remove all pop-ups.

**Comment by manofspirit** [comment] 2015-09-28 17:39
what i currently need is know whether there are any popups or not, this way i can hide classic flash content which always appear over popups. 

if(PopupManager.popups.length > 0)
hideFlashContent

**Comment by joshtynjala** [comment] 2015-09-28 17:43
Here's one way that you can provide your own value for PopUpManager.root:

	var popUpRoot:Sprite = new Sprite();
	Starling.current.stage.addChild(popUpRoot);
	PopUpManager.root = popUpRoot

Then, you can check if the value of numChildren is greater than 0.

	if(PopUpManager.root.numChildren > 0)
	{
		//hide flash content
	}

**Comment by joshtynjala** [comment] 2015-10-28 21:52
Cleaning up as duplicate of #794

**Closed by joshtynjala** 2015-10-28 21:52 UTC
Labels: enhancement
