### ISSUE TITLE
No clear scrolling of list

### ISSUE THREAD

**Issue by denisgl777** [BowlerHatLLC/feathers#1650] opened 2017-11-09 08:39 UTC
The situation is as follows
I create a List with different elements
```
var layoutForMessagesList:VerticalLayout = new VerticalLayout();
layoutForMessagesList.hasVariableItemDimensions = true;
layoutForMessagesList.horizontalAlign = HorizontalAlign.JUSTIFY;
layoutForMessagesList.gap = 15;
layoutForMessagesList.paddingBottom = 15;
layoutForMessagesList.paddingLeft = 10;
layoutForMessagesList.paddingRight = 10;

messagesList.setItemRendererFactoryWithID(Config.TYPE_MESSEGE, function():IListItemRenderer
{
	var itemRenderer:ChatMessageItemRenderer = new ChatMessageItemRenderer();
	itemRenderer.textureCache = avatarCache;
	return itemRenderer;
});
			
messagesList.setItemRendererFactoryWithID(Config.TYPE_MY_MESSEGE, function():IListItemRenderer
{
         var itemRenderer:MyChatMessageItemRenderer = new MyChatMessageItemRenderer();
	itemRenderer.textureCache = avatarCache;
	return itemRenderer;
});
			
messagesList.setItemRendererFactoryWithID(Config.TYPE_DATA, function():IListItemRenderer
{
	var itemRenderer:ChatDataItemRenderer = new ChatDataItemRenderer();
	return itemRenderer;
});
```

inside the items I create messages
```

horizontalLayout = new HorizontalLayout();
horizontalLayout.horizontalAlign = HorizontalAlign.RIGHT;
horizontalLayout.verticalAlign = VerticalAlign.TOP;
horizontalLayout.gap = 5;
this.layout = horizontalLayout;

messageLabel = new Label();
messageLabel.styleNameList.add('message_label');
messageLabel.minWidth = 5;
messageLabel.minHeight = 5;
			
messageLabel.wordWrap = true;
//messageLabel.maxWidth = stage.stageWidth * 0.6;
```

if you do not specify an explicit or maximum message size, you get this situation
https://ibb.co/gyVxXb
if you set the maximum size
https://ibb.co/d9W4Cb
but in this case the twitch jerks when scrolling list

**Comment by denisgl777** [comment] 2017-11-12 22:16
At the same time, scrolling down the list does not cause problems. And when scrolling up as if jumping to several points

**Comment by joshtynjala** [comment] 2017-11-13 16:33
It's difficult to guess what's wrong without seeing the code for your custom item renderer.

I just modified the Magic8Chat example app to set wordWrap = true on the item renderers, and I could scroll up smoothly. It seems most likely that something in your custom item renderer may be causing it to resize unexpectedly when you scroll, and that is causing the layout to "thrash". You might want to check that you aren't doing anything that might cause the item renderer to resize too often.

**Comment by denisgl777** [comment] 2017-11-13 17:49
```
override protected function initialize():void
{
			
	super.initialize();
			
	horizontalLayout = new HorizontalLayout();
	horizontalLayout.horizontalAlign = HorizontalAlign.RIGHT;
	horizontalLayout.verticalAlign = VerticalAlign.TOP;
	horizontalLayout.gap = 5;
	this.layout = horizontalLayout;
			
	var avatarMask:Canvas = new Canvas();
			
	var radius:Number = 15;
	avatarMask.drawCircle(radius, radius, radius);
			
	avatar = new ImageLoader();
	avatar.width = avatar.height = radius * 2;
	avatar.mask = avatarMask;
			
	bubble = RoundedRect.createRoundedRect(0xFFFFFF);
			
	messageGroup = new LayoutGroup();
	var messageLayout:VerticalLayout = new VerticalLayout();
	messageLayout.horizontalAlign = HorizontalAlign.LEFT;
	messageLayout.verticalAlign = VerticalAlign.TOP;
	messageLayout.paddingLeft = messageLayout.paddingRight = 
        messageLayout.paddingTop = messageLayout.paddingBottom = 5;
	messageGroup.layout = messageLayout;
	messageGroup.backgroundSkin = bubble;
			
	nameLabel = new Label();
	nameLabel.styleNameList.add('name_label');
	messageGroup.addChild(nameLabel);
			
	messageLabel = new Label();
	messageLabel.styleNameList.add('message_label');
	messageLabel.minWidth = 5;
	messageLabel.minHeight = 5;
	messageLabel.maxWidth = stage.stageWidth * 0.7;
	messageLabel.wordWrap = true;
	messageGroup.addChild(messageLabel);
			
	timeLabel = new Label();
	timeLabel.styleNameList.add('time_label');
			
	this.addChild(timeLabel);
	this.addChild(messageGroup);
	this.addChild(avatar);
		
	}
```
There is nothing here that could change its size very often

**Comment by joshtynjala** [comment] 2017-11-14 16:05
I tried running your code, but scrolling was nice and smooth.

Could it be that the avatar ImageLoader is loading very large images? Uploading a texture to the GPU will cause rendering to pause, and larger images will result in longer pauses. Be sure to load thumbnails that aren't much larger than the width and height of the avatar ImageLoader.

**Comment by denisgl777** [comment] 2017-11-14 16:39
I removed the avatar and nothing has changed.
I'm more than sure that the problem is in the label element. Leaving the pure text still have problems with the scrolling.
Only if you set messageLabel.wordWrap = false;
The problem disappears

**Comment by joshtynjala** [comment] 2017-11-14 16:42
Yes, that seems likely. Unfortunately, I don't have any further suggestions because I still cannot reproduce this issue.

**Comment by denisgl777** [comment] 2017-11-14 17:03
can I create an example for you?

**Comment by joshtynjala** [comment] 2017-11-14 18:22
It's strange because the messageGroup was in your sample code, and it did not cause the same issue for me.

You might try keeping the messageGroup, but remove it's background skin:

> bubble = RoundedRect.createRoundedRect(0xFFFFFF);
> messageGroup.backgroundSkin = bubble;

I commented these lines out when I tested because I don't have your RoundedRect class. Depending on what this class is doing, it could potentially be the reason why you're seeing bad performance.

**Comment by denisgl777** [comment] 2017-11-14 18:34
Josh, I already went through all the options
If I discard internal containers and use AnchorLayot, then everything works like clockwork
```
protected var messageLabel:Label;
protected var nameLabel:Label;
private var messageGroup:LayoutGroup;
private var horizontalLayout:HorizontalLayout;
override protected function initialize():void
{
			
	super.initialize();
			
	horizontalLayout = new HorizontalLayout();
	horizontalLayout.horizontalAlign = HorizontalAlign.RIGHT;
	horizontalLayout.verticalAlign = VerticalAlign.TOP;
	horizontalLayout.gap = 5;
	this.layout = horizontalLayout;
			
	messageGroup = new LayoutGroup();
	var messageLayout:VerticalLayout = new VerticalLayout();
	messageLayout.horizontalAlign = HorizontalAlign.LEFT;
	messageLayout.verticalAlign = VerticalAlign.TOP;
	messageLayout.paddingLeft = messageLayout.paddingRight = messageLayout.paddingTop = messageLayout.paddingBottom = 5;
	messageGroup.layout = messageLayout;
			
	nameLabel = new Label();
	nameLabel.styleNameList.add('name_label');
	messageGroup.addChild(nameLabel);
			
	messageLabel = new Label();
	messageLabel.styleNameList.add('message_label');
	messageLabel.minWidth = 5;
	messageLabel.minHeight = 5;
	messageLabel.maxWidth = stage.stageWidth * 0.7;
	messageLabel.wordWrap = true;
			
	messageGroup.addChild(messageLabel);
			
	this.addChild(messageGroup);
}
```
I've reduced the code to a minimum where I can get problems when scrolling. And I get them

**Comment by joshtynjala** [comment] 2017-11-14 18:43
It's still smooth as butter for me with your new sample code. There must be some other detail about your project that is causing it. However, since you say that you've found a workaround by using AnchorLayout, I'll close this issue.

**Closed by joshtynjala** 2017-11-14 18:43 UTC

**Comment by denisgl777** [comment] 2017-11-14 20:36
Even with this code, I have problems with scrolling long messages in a few lines. I'm still sure that there is a problem. Once I discard the containers - the problem disappears
```
public class MyChatMessageItemRenderer extends LayoutGroupListItemRenderer
	{
		
		
		protected var messageLabel:Label;
		protected var nameLabel:Label;
		private var messageGroup:LayoutGroup;
		private var horizontalLayout:HorizontalLayout;
		override protected function initialize():void
		{
			
			super.initialize();		
			
			messageGroup = new LayoutGroup();
			messageLabel = new Label();
			messageLabel.styleNameList.add('personal_label');
			messageLabel.width = stage.stageWidth * 0.7;
			messageLabel.wordWrap = true;
			messageGroup.addChild(messageLabel);
			this.addChild(messageGroup);
		}
		
		override protected function commitData():void
		{
			if (this._data && this._owner)
			{
				messageLabel.text = this._data.message;
			}
		}
	}
```
```
	var layoutForMessagesList:VerticalLayout = new VerticalLayout();
			layoutForMessagesList.hasVariableItemDimensions = true;
			var messageLayoutData:AnchorLayoutData = new AnchorLayoutData(0, 0, 0, 0);
			messagesList = new List();
			messagesList.layout = layoutForMessagesList;
			messagesList.layoutData = messageLayoutData;
			messagesList.itemRendererFactory = function():IListItemRenderer
			{
				var itemRenderer:MyChatMessageItemRenderer = new MyChatMessageItemRenderer();
				return itemRenderer
			};
			this.addChild(messagesList);
```

**Comment by joshtynjala** [comment] 2017-11-14 20:50
I don't think we're going to get anywhere focusing on these small snippets of code. Can you make a *simple* project based on that code and attach it here?

**Comment by denisgl777** [comment] 2017-11-14 21:01
I'll make a simple project for you tomorrow afternoon :)

**Comment by denisgl777** [comment] 2017-11-15 12:52
Josh, did you get my project?

**Comment by joshtynjala** [comment] 2017-11-15 14:44
@denisgl777 Received, but I need permission to access it.

**Comment by denisgl777** [comment] 2017-11-15 14:57
Sorry Josh :) I made a link for you in private messages on the forum. If you can not go on it, let me know!

**Comment by joshtynjala** [comment] 2017-11-15 16:46
So what's happening here is that you're changing the text of the Label because the item renderer is being reused for a different item. However, the Label doesn't actually dispatch Event.RESIZE until it validates. Until the Label resizes, its parent LayoutGroup doesn't know that it should also resize. So the item renderer is telling the LayoutGroup to validate, but the LayoutGroup is basically saying "I don't see any changes, so I don't need to validate right now. I'm the exact same size as before". A moment later, the Label validates and dispatches Event.RESIZE, which invalidates the LayoutGroup. However, by that point, it's too late because the layout has already used the dimensions of the old text.

Your best option is to manually invalidate the messageGroup when you change the text of the messageLabel, like this:

``` actionscript
override protected function commitData():void
{
	if (this._data && this._owner)
	{
		messageLabel.text = this._data.message;
		messageGroup.invalidate(INVALIDATION_FLAG_LAYOUT);
	}
}
```

**Comment by denisgl777** [comment] 2017-11-15 20:23
thanks Josh!
