### ISSUE TITLE
Scroller:verticalAutoScrollTween_onComplete() NPE

### ISSUE THREAD

**Issue by teotigraphix** [BowlerHatLLC/feathers#1641] opened 2017-10-02 13:12 UTC
Sorry I cannot reproduce a test case but I thought I would tell you that it IS possible to get a null pointer here.

Seems that `_verticalAutoScrollTween` is null.

 This is the client code that produced it;

```
var vsp:Number = pitchIndex * view.pianoRoll.maxVerticalScrollPosition / view.pianoRoll.trackHeight;
view.pianoRoll.scrollToPosition(view.pianoRoll.horizontalScrollPosition, vsp, 0.5);
view.pianoRollKeyboard.scrollToPosition(view.pianoRoll.horizontalScrollPosition, vsp, 0.5);
```

**Comment by teotigraphix** [comment] 2017-10-02 13:17
Actually I just noticed an error on my part.

pianoRoll.horizontalScrollPosition should have been pianoRollKeyboard.horizontalScrollPosition in the last call.

These actually should be the same value but might not be. So it looks like the NPE could come from a hscroll position being invalid called from Scroller.scrollToPosition().

**Comment by joshtynjala** [comment] 2017-10-02 15:23
Someone mentioned a similar null reference error with _horizontalAutoScrollTween the other day, but they also didn't know how to reproduce. I'll see if I can figure it out. If not, someone will eventually figure it out.

**Comment by joshtynjala** [comment] 2017-10-03 15:56
Are you using version 3.3.0? Or are you still on an older version?

**Comment by teotigraphix** [comment] 2017-10-03 16:40
3.3.0 SDK

**Comment by joshtynjala** [comment] 2017-10-03 16:48
Thanks. I was hoping you were still on 3.2, since there was a similar bug fixed in 3.3.

Well, I can't seem to reproduce, so I guess we wait until someone finds more clues.

**Comment by teotigraphix** [comment] 2017-10-03 18:01
Thanks, yeah no problem! I will actually put it back in the state it threw the bug to see if I can see any root cause that I could pass on to you.

This is another complicated app on the UI end, thus really hard to pin point but again, since the actual bug comes around on a validation cycle, even harder. :)

**Comment by barksdontduck** [comment] 2017-10-25 17:30
I was having this issue. Not sure if this will help, but I'll add it anyway:

I have a socket-based networking layer. In iOS, the app goes into the background, and the UI needs to stop rendering. A call like this will always throw the exception:

chatList.scrollToPosition(NaN, chatList.maxVerticalScrollPosition, .1);

You can wrap it in SystemUtil.executeWhenApplicationIsActive and it still does it.

The solution for me was to set the scroll position manually, and not use the above tween function. (It wasn't enough to check if the app is still active before that call either.)

**Comment by teotigraphix** [comment] 2017-11-13 19:47
Another one

```
feathers.controls::Scroller/verticalAutoScrollTween_onComplete	
Function/http://adobe.com/AS3/2006/builtin::apply [no source]	
starling.animation::Tween/advanceTime	
feathers.controls::Scroller/verticalAutoScrollTween_onUpdate	
feathers.controls::Scroller/verticalAutoScrollTween_onUpdateWithEndRatio	
Function/http://adobe.com/AS3/2006/builtin::apply [no source]	
starling.animation::Tween/advanceTime	
starling.animation::Juggler/advanceTime	
starling.core::Starling/advanceTime	
starling.core::Starling/nextFrame	
starling.core::Starling/onEnterFrame	
```

This was using the scroll wheel of a mouse.

This really is random, the null happens at the end of the tween when the list finishes.

**Comment by teotigraphix** [comment] 2017-11-13 19:48
Here is the full stat of that List right when the error occured;

```
this	List (@1f5ab0a1)	
	[inherited]	
		actualHeight	440.00000000000006	
		actualHorizontalScrollStep	54.8	
		actualMinHeight	440.00000000000006	
		actualMinWidth	1024 [0x400]	
		actualPageHeight	432.00000000000006	
		actualPageWidth	1024 [0x400]	
		actualVerticalScrollStep	54.8	
		actualWidth	1024 [0x400]	
		alpha	1	
		_alpha	1	
		_applyingStyles	false	
		autoHideBackground	false	
		_autoHideBackground	false	
		backgroundDisabledSkin	null	
		_backgroundDisabledSkin	null	
		backgroundSkin	Quad (@1f67cca1)	
		_backgroundSkin	Quad (@1f67cca1)	
		base	Stage (@15c09101)	
		blendMode	"auto"	
		_blendMode	"auto"	
		_bottomPullTween	null	
		bottomPullView	null	
		_bottomPullView	null	
		bottomPullViewDisplayMode	"drag"	
		_bottomPullViewDisplayMode	"drag"	
		bottomPullViewRatio	0	
		_bottomPullViewRatio	0	
		_bottomViewPortOffset	0	
		bounds	Rectangle (@122f5281)	
		_children	Vector.<starling.display::DisplayObject> (@1f5f5791)	
		clipContent	true	
		_clipContent	true	
		currentBackgroundSkin	Quad (@1f67cca1)	
		_currentTouchX	132 [0x84]	
		_currentTouchY	86 [0x56]	
		customHorizontalScrollBarStyleName	null	
		_customHorizontalScrollBarStyleName	null	
		customVerticalScrollBarStyleName	null	
		_customVerticalScrollBarStyleName	null	
		decelerationRate	0.998	
		_decelerationRate	0.998	
		defaultStyleProvider	ConditionalStyleProvider (@1aa45141)	
		defaultTextEditorFactory	Function (@c622791)	
		defaultTextRendererFactory	Function (@c622761)	
		_delayedInvalidationFlags	Object (@1f5ed419)	
		depth	4	
		_depth	4	
		elasticity	0.33	
		_elasticity	0.33	
		elasticSnapDuration	0.5	
		_elasticSnapDuration	0.5	
		_eventListeners	Dictionary (@1f5ed629)	
		_eventStack	Vector.<String> (@1f5f5761)	
		_explicitBackgroundHeight	48 [0x30]	
		_explicitBackgroundMaxHeight	48 [0x30]	
		_explicitBackgroundMaxWidth	48 [0x30]	
		_explicitBackgroundMinHeight	48 [0x30]	
		_explicitBackgroundMinWidth	48 [0x30]	
		_explicitBackgroundWidth	48 [0x30]	
		explicitHeight	440.00000000000006	
		_explicitHeight	440.00000000000006	
		explicitHorizontalScrollStep	NaN	
		explicitMaxHeight	486 [0x1e6]	
		_explicitMaxHeight	486 [0x1e6]	
		explicitMaxWidth	Infinity	
		_explicitMaxWidth	Infinity	
		explicitMinHeight	NaN	
		_explicitMinHeight	NaN	
		explicitMinWidth	NaN	
		_explicitMinWidth	NaN	
		explicitPageHeight	NaN	
		explicitPageWidth	NaN	
		explicitVerticalScrollStep	NaN	
		_explicitViewPortHeight	NaN	
		_explicitViewPortMinHeight	NaN	
		_explicitViewPortMinWidth	NaN	
		_explicitViewPortWidth	NaN	
		explicitWidth	1024 [0x400]	
		_explicitWidth	1024 [0x400]	
		filter	null	
		_filter	null	
		_fixedThrowDuration	2.996998998998728	
		focusIndicatorSkin	null	
		_focusIndicatorSkin	null	
		focusManager	null	
		_focusManager	null	
		focusOwner	null	
		_focusOwner	null	
		focusPadding	0	
		focusPaddingBottom	0	
		_focusPaddingBottom	0	
		focusPaddingLeft	0	
		_focusPaddingLeft	0	
		focusPaddingRight	0	
		_focusPaddingRight	0	
		focusPaddingTop	0	
		_focusPaddingTop	0	
		hasElasticEdges	true	
		_hasElasticEdges	true	
		_hasFocus	false	
		_hasHorizontalScrollBar	false	
		hasPendingHorizontalPageIndex	false	
		hasPendingVerticalPageIndex	false	
		_hasValidated	true	
		_hasVerticalScrollBar	true	
		_hasViewPortBoundsChanged	true	
		_hasVisibleArea	true	
		height	440.00000000000006	
		hideScrollBarAnimationDuration	0.2	
		_hideScrollBarAnimationDuration	0.2	
		hideScrollBarAnimationEase	"easeOut"	
		_hideScrollBarAnimationEase	"easeOut"	
		_hitArea	Rectangle (@1f5f5f41)	
		_horizontalAutoScrollTween	null	
		_horizontalAutoScrollTweenEndRatio	1	
		horizontalPageCount	1	
		horizontalPageIndex	0	
		_horizontalPageIndex	0	
		horizontalScrollBar	SimpleScrollBar (@1f660cf1)	
		horizontalScrollBarFactory	<getter>	
		_horizontalScrollBarFactory	Function (@1e1c4bb1)	
		_horizontalScrollBarHideTween	null	
		_horizontalScrollBarIsScrolling	false	
		horizontalScrollBarPosition	"bottom"	
		_horizontalScrollBarPosition	"bottom"	
		horizontalScrollBarProperties	PropertyProxy (@123b5831)	
		_horizontalScrollBarProperties	null	
		horizontalScrollBarStyleName	"feathers-scroller-horizontal-scroll-bar"	
		_horizontalScrollBarTouchPointID	-1 [0xffffffff]	
		horizontalScrollPolicy	"auto"	
		_horizontalScrollPolicy	"auto"	
		horizontalScrollPosition	0	
		_horizontalScrollPosition	0	
		horizontalScrollStep	54.8	
		id	"$list"	
		_id	"$list"	
		_ignoreNextStyleRestriction	false	
		ignoreViewPortResizing	false	
		includeInLayout	true	
		_includeInLayout	true	
		interactionMode	"touch"	
		_interactionMode	"touch"	
		_invalidateCount	0	
		_invalidationFlags	Object (@1f5ed329)	
		is3D	false	
		_is3D	false	
		_isAllInvalid	false	
		isBottomPullViewActive	false	
		_isBottomPullViewActive	false	
		_isBottomPullViewPending	false	
		isCreated	true	
		_isDisposed	false	
		_isDraggingHorizontally	false	
		_isDraggingVertically	false	
		isEnabled	true	
		_isEnabled	true	
		isFocusEnabled	true	
		_isFocusEnabled	true	
		isInitialized	true	
		_isInitialized	true	
		_isInitializing	false	
		isLeftPullViewActive	false	
		_isLeftPullViewActive	false	
		_isLeftPullViewPending	false	
		isMask	false	
		isQuickHitAreaEnabled	false	
		_isQuickHitAreaEnabled	false	
		isRightPullViewActive	false	
		_isRightPullViewActive	false	
		_isRightPullViewPending	false	
		isRotated	false	
		isScrollBarRevealPending	false	
		isScrolling	false	
		_isScrolling	false	
		_isScrollingStopped	false	
		isTopPullViewActive	false	
		_isTopPullViewActive	false	
		_isTopPullViewPending	false	
		_isValidating	false	
		_lastChildChangeFrameID	212 [0xd4]	
		_lastParentOrSelfChangeFrameID	212 [0xd4]	
		_lastViewPortHeight	657.5999999999999	
		_lastViewPortWidth	1024 [0x400]	
		layoutData	VerticalLayoutData (@1f6097b9)	
		_layoutData	VerticalLayoutData (@1f6097b9)	
		_leftPullTween	null	
		leftPullView	null	
		_leftPullView	null	
		leftPullViewDisplayMode	"drag"	
		_leftPullViewDisplayMode	"drag"	
		leftPullViewRatio	0	
		_leftPullViewRatio	0	
		_leftViewPortOffset	0	
		_logDecelerationRate	-0.0020020026706730793	
		mask	null	
		_mask	null	
		_maskee	null	
		maskInverted	false	
		_maskInverted	false	
		maxHeight	486 [0x1e6]	
		maxHorizontalPageIndex	0	
		_maxHorizontalPageIndex	0	
		maxHorizontalScrollPosition	0	
		_maxHorizontalScrollPosition	0	
		maxVerticalPageIndex	0	
		_maxVerticalPageIndex	0	
		maxVerticalScrollPosition	225.59999999999985	
		_maxVerticalScrollPosition	225.59999999999985	
		maxWidth	Infinity	
		measureViewPort	true	
		_measureViewPort	true	
		minHeight	440.00000000000006	
		minHorizontalPageIndex	0	
		_minHorizontalPageIndex	0	
		minHorizontalScrollPosition	0	
		_minHorizontalScrollPosition	0	
		minimumDragDistance	0.04	
		_minimumDragDistance	0.04	
		minimumPageThrowVelocity	5	
		_minimumPageThrowVelocity	5	
		minTouchHeight	0	
		_minTouchHeight	0	
		minTouchWidth	0	
		_minTouchWidth	0	
		minVerticalPageIndex	0	
		_minVerticalPageIndex	0	
		minVerticalScrollPosition	0	
		_minVerticalScrollPosition	0	
		minWidth	1024 [0x400]	
		mouseWheelScrollDuration	0.35	
		_mouseWheelScrollDuration	0.35	
		name	null	
		_name	null	
		nextTabFocus	null	
		_nextTabFocus	null	
		numChildren	4	
		numRawChildrenInternal	4	
		padding	8	
		paddingBottom	0	
		_paddingBottom	0	
		paddingLeft	0	
		_paddingLeft	0	
		paddingRight	0	
		_paddingRight	0	
		paddingTop	8	
		_paddingTop	8	
		pageHeight	432.00000000000006	
		pageThrowDuration	0.5	
		_pageThrowDuration	0.5	
		pageWidth	1024 [0x400]	
		parent	FileListPane (@1f622851)	
		_parent	FileListPane (@1f622851)	
		pendingHorizontalPageIndex	0	
		pendingHorizontalScrollPosition	NaN	
		pendingScrollDuration	NaN	
		_pendingVelocityChange	false	
		pendingVerticalPageIndex	0	
		pendingVerticalScrollPosition	NaN	
		pivotX	0	
		_pivotX	0	
		pivotY	0	
		_pivotY	0	
		_popToken	BatchToken (@1f624d61)	
		previousTabFocus	null	
		_previousTabFocus	null	
		_previousTouchTime	10165 [0x27b5]	
		_previousTouchX	132 [0x84]	
		_previousTouchY	86 [0x56]	
		_previousVelocityX	Vector.<Number> (@1f5f5e51)	
		_previousVelocityY	Vector.<Number> (@1f5f5e81)	
		_pushToken	BatchToken (@1f624d41)	
		requiresRedraw	true	
		_restrictedStyles	Dictionary (@1f5ed9e9)	
		revealScrollBarsDuration	1	
		_revealScrollBarsDuration	1	
		_rightPullTween	null	
		rightPullView	null	
		_rightPullView	null	
		rightPullViewDisplayMode	"drag"	
		_rightPullViewDisplayMode	"drag"	
		rightPullViewRatio	0	
		_rightPullViewRatio	0	
		_rightViewPortOffset	0	
		root	FileDialog (@1f5a40a1)	
		rotation	0	
		_rotation	0	
		sAncestors	Vector.<starling.display::DisplayObject> (@35a5221)	
		sBroadcastListeners	Vector.<starling.display::DisplayObject> (@35a5551)	
		sBubbleChains	[] (@9590041)	
		sCacheToken	BatchToken (@c6410c1)	
		scale	1	
		scaledActualHeight	440.00000000000006	
		scaledActualMinHeight	440.00000000000006	
		scaledActualMinWidth	1024 [0x400]	
		scaledActualWidth	1024 [0x400]	
		scaleX	1	
		_scaleX	1	
		scaleY	1	
		_scaleY	1	
		scrollBarDisplayMode	"float"	
		_scrollBarDisplayMode	"float"	
		sHelperMatrix	Matrix (@953e141)	
		sHelperMatrix3D	Matrix3D (@c5351e9)	
		sHelperMatrixAlt	Matrix (@953e181)	
		sHelperMatrixAlt3D	Matrix3D (@c535191)	
		sHelperPoint	Point (@c641061)	
		sHelperPoint3D	Vector3D (@35a54c1)	
		sHelperPointAlt3D	Vector3D (@35a54f1)	
		sHelperRect	Rectangle (@35a5521)	
		_showFocus	false	
		skewX	0	
		_skewX	0	
		skewY	0	
		_skewY	0	
		sMaskWarningShown	true	
		_snapOnComplete	false	
		snapScrollPositionsToPixels	true	
		_snapScrollPositionsToPixels	true	
		snapToPages	false	
		_snapToPages	false	
		sSortBuffer	Vector.<starling.display::DisplayObject> (@35a55b1)	
		stage	Stage (@15c09101)	
		_startHorizontalScrollPosition	0	
		_startTouchX	131 [0x83]	
		_startTouchY	85 [0x55]	
		_startVerticalScrollPosition	0	
		styleName	"file-list-list"	
		styleNameList	TokenList (@1f624d21)	
		_styleNameList	TokenList (@1f624d21)	
		styleProvider	ConditionalStyleProvider (@1aa45141)	
		_styleProvider	ConditionalStyleProvider (@1aa45141)	
		_targetHorizontalScrollPosition	NaN	
		_targetVerticalScrollPosition	225.59999999999997	
		throwEase	<getter>	
		_throwEase	Function (@1dc05ca1)	
		throwElasticity	0.05	
		_throwElasticity	0.05	
		_tokenFrameID	4294967295 [0xffffffff]	
		toolTip	null	
		_toolTip	null	
		_topPullTween	null	
		topPullView	null	
		_topPullView	null	
		topPullViewDisplayMode	"drag"	
		_topPullViewDisplayMode	"drag"	
		topPullViewRatio	0	
		_topPullViewRatio	0	
		_topViewPortOffset	8	
		touchable	true	
		_touchable	true	
		_touchBlocker	Quad (@1f712d79)	
		touchGroup	false	
		_touchGroup	false	
		_touchPointID	-1 [0xffffffff]	
		_transformationChanged	false	
		transformationMatrix	Matrix (@1f5a7181)	
		_transformationMatrix	Matrix (@1f5a7181)	
		transformationMatrix3D	Matrix3D (@1f6ed2f1)	
		_transformationMatrix3D	null	
		useFixedThrowDuration	true	
		_useFixedThrowDuration	true	
		useHandCursor	false	
		_useHandCursor	false	
		_validationQueue	ValidationQueue (@15d587a1)	
		_velocityX	0	
		_velocityY	0	
		_verticalAutoScrollTween	null	
		_verticalAutoScrollTweenEndRatio	0.9999999999999994	
		verticalMouseWheelScrollDirection	"vertical"	
		_verticalMouseWheelScrollDirection	"vertical"	
		verticalMouseWheelScrollStep	NaN	
		_verticalMouseWheelScrollStep	NaN	
	allowMultipleSelection	false	
	_allowMultipleSelection	false	
	customItemRendererStyleName	null	
	_customItemRendererStyleName	null	
	dataProvider	VectorCollection (@1f609331)	
	_dataProvider	VectorCollection (@1f609331)	
	dataViewPort	ListDataViewPort (@1f5a66d1)	
	factoryIDFunction	null	
	_factoryIDFunction	null	
	globalStyleProvider	ConditionalStyleProvider (@1aa45141)	
	isChildFocusEnabled	true	
	_isChildFocusEnabled	true	
	isSelectable	true	
	_isSelectable	true	
	_itemRendererFactories	null	
	itemRendererFactory	<getter>	
	_itemRendererFactory	Function (@1f7170a1)	
	itemRendererProperties	PropertyProxy (@123b53f9)	
	_itemRendererProperties	null	
	itemRendererType	Object (@c5ba0e9)	
	_itemRendererType	Object (@c5ba0e9)	
	keyScrollDuration	0.25	
	_keyScrollDuration	0.25	
	layout	VerticalLayout (@c5ba971)	
	_layout	VerticalLayout (@c5ba971)	
	pendingItemIndex	-1 [0xffffffff]	
	selectedIndex	-1 [0xffffffff]	
	_selectedIndex	-1 [0xffffffff]	
	selectedIndices	Vector.<int> (@1f6dc581)	
	_selectedIndices	ListCollection (@1f5f5dc1)	
	selectedItem	null	
	selectedItems	Vector.<Object> (@1f5f5e21)	
	_selectedItems	Vector.<Object> (@1f5f5e21)	
	typicalItem	null	
	_typicalItem	null	
```

**Comment by teotigraphix** [comment] 2017-11-13 19:52
This bug is really starting to suck.

I think you need to put a null check in there for your next release.

In `verticalAutoScrollTween_onComplete()`

I am guessing this bug was introduced at some point when you added pull refreshing or something.

**Closed** 2017-11-14 15:46 UTC
Labels: bug
