### ISSUE TITLE
Getting out of range exceptions calling list.dataProvider.getItemAt(list.horizontalPageIndex);

### ISSUE THREAD

**Issue by mariommoreno** [BowlerHatLLC/feathers#1275] opened 2016-01-22 16:39 UTC
It's hard to reproduce. Only a few users are reporting this exception. 
Is it even possible? 
I think it started after updating to "2.3.0".

````
this.list.addEventListener(FeathersEventType.SCROLL_COMPLETE, scrollCompleteHandler);
private function scrollCompleteHandler(e:Event = null):void 
{
	var item:Object = list.dataProvider.getItemAt(list.horizontalPageIndex);
	[...]
}
````

**Comment by joshtynjala** [comment] 2016-01-22 18:59
> It's hard to reproduce. Only a few users are reporting this exception. 

This may be difficult to fix if I cannot reproduce it easily. I will investigate, though. Maybe I'll get lucky.

>  Is it even possible?

It could happen if the horizontalPageIndex value reported by the List were incorrect. Sometimes, calculations with floating point numbers can be inaccurate. I've fixed a similar issue before, but maybe there is another place where a floating point calculation error could occur. Perhaps with the calculation of maxHorizontalPageIndex or minHorizontalPageIndex.

It might help to know whether the horizontalPageIndex value is < 0 or >= dataProvider.length. Please consider posting the full text of the runtime error too. Every little bit of information could be helpful.

**Comment by joshtynjala** [comment] 2016-02-03 18:14
I tried with the following code, but I could not reproduce:

	var layout:HorizontalLayout = new HorizontalLayout();
	var list:List = new List();
	list.snapToPages = true;
	list.layout = layout;
	list.itemRendererFactory = function():IListItemRenderer
	{
		var itemRenderer:DefaultListItemRenderer = new DefaultListItemRenderer();
		itemRenderer.setSize(stage.stageWidth, stage.stageHeight);
		return itemRenderer;
	};
	list.dataProvider = new ListCollection(
	[
		{ label: "0" },
		{ label: "1" },
		{ label: "2" },
		{ label: "3" },
		{ label: "4" },
		{ label: "5" },
		{ label: "6" },
		{ label: "7" },
		{ label: "8" },
		{ label: "9" },
	]);
	list.setSize(stage.stageWidth, stage.stageHeight);
	this.addChild(list);

	list.addEventListener(FeathersEventType.SCROLL_COMPLETE, function(e:Event = null):void
	{
		var item:Object = list.dataProvider.getItemAt(list.horizontalPageIndex);
	});

If you can provide the values of horizontalPageIndex, minHorizontalPageIndex, maxHorizontalPageIndex, horizontalScrollPosition, minHorizontalScrollPosition, and maxHorizontalScrollPosition when the error occurs, that might help.

For now, I'll just close this. We can reopen if we figure out how to reproduce.

**Closed by joshtynjala** 2016-02-03 18:14 UTC
Labels: bug
