### ISSUE TITLE
TextBlockTextRenderer: ArgumentError: Error #2015: Invalid BitmapData.

### ISSUE THREAD

**Issue by joshtynjala** [BowlerHatLLC/feathers#1302] opened 2016-02-29 18:43 UTC
Can reproduce with the following code:

	new MetalWorksMobileTheme();
	
	var button:Button = new Button();
	button.label = "Test";
	button.height = 0;
	this.addChild(button);

Did not work by instantiating TextBlockTextRenderer directly and setting its height to 0. Similarly, it did not work with Label.

**Comment by teotigraphix** [comment] 2016-02-29 18:48
I got this a bunch of times and really didn't think it was a bug, since I pretty much figured I needed to have a non 0 height for text.

**Comment by joshtynjala** [comment] 2016-02-29 18:55
Generally, it doesn't make much sense to have text with a height of 0. However, I think that sometimes people want to start animations at 0, and maybe there are other edge cases where it should be allowed. At the very least, I'd like to avoid confusion.

**Comment by teotigraphix** [comment] 2016-02-29 18:58
Right I didn't say it's not a bug I just rationalized it as I was learning layouts that I shouldn't have text at 0, I thought it had something to do with the actual lower level implementation.

**Comment by Klug76** [comment] 2016-02-29 19:06
perhaps it is a duplicate of https://github.com/BowlerHatLLC/feathers/issues/1278?

**Comment by joshtynjala** [comment] 2016-02-29 19:11
Yes, that's probably the same issue.

Strangely, I thought that TextBlockTextRenderer already accounted for texture snapshots that are too small. Based on your comments in the other issue, @Klug76, it seems like it is related to the power-of-two textures required by Context3DProfile.BASELINE_CONSTRAINED. I'll investigate further soon.

**Closed** 2016-03-09 00:58 UTC
Labels: bug
